### ISSUE TITLE
Update sdk and device profile

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/device-random#79]
1. Update device SDK to the latest version
2. Use "deviceResource" in preference to "object". see [go-mod-core-contracts#114](https://github.com/edgexfoundry/go-mod-core-contracts/issues/114)
3. Remove  the unnecessary parameter fields:
  ```
deviceCommands:
-
  name: "GenerateRandomValue_Int8"
  get:
  - { operation: "get", object: "RandomValue_Int8", parameter: "RandomValue_Int8" }
  set:
  - { operation: "set", object: "Min_Int8", parameter: "Min_Int8" }
  - { operation: "set", object: "Max_Int8", parameter: "Max_Int8" }
  ```
